# Docker Compose file for webapp-service

services:
  webapp-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: webapp-service
    ports:
      - "3000:80"
    environment:
      - VITE_DRAFT_SERVICE_URL=http://draft-service:8080
      - VITE_PUBLISHER_SERVICE_URL=http://publisher-service:8080
      - VITE_JAEGER_ENDPOINT=http://jaeger:4318/v1/traces
    networks:
      - happy-headlines
      - observability

networks:
  happy-headlines:
    external: false
    name: happy-headlines
  observability:
    external: true
    name: happyheadlines-observability
